version: '3'
services:
    web-api:
        image: nginx
        volumes:
        - "./docker/etc/nginx/default.conf:/etc/nginx/conf.d/default.template"
        - "./:/var/www/html"
        ports:
        - "9882:80"
        environment:
        - NGINX_HOST=${NGINX_HOST_API}
        command: /bin/bash -c "envsubst '$$NGINX_HOST' < /etc/nginx/conf.d/default.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
        restart: always
        depends_on:
        - php-api
    php-api:
        image: php:7.2-fpm
        restart: always
        depends_on:
            - composer
        volumes:
            - "./:/var/www/html"
    composer:
        image: composer:1.6
        working_dir: /app
        volumes:
            - "./:/app"
        command: install
    mysqldb:
        image: mysql:${MYSQL_VERSION}
        container_name: ${MYSQL_HOST}
        restart: always
        env_file:
        - ".env"
        environment:
        - MYSQL_DATABASE=${MYSQL_DATABASE}
        - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
        - MYSQL_USER=${MYSQL_USER}
        - MYSQL_PASSWORD=${MYSQL_PASSWORD}
        ports:
        - "8989:3306"
        volumes:
        - "./data/db/mysql:/var/lib/mysql"